spring:
  cloud:
    nacos:
      discovery:
        server-addr: mall-nacos:8848
  application:
    name: mall-ware
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000